const NPM_PROVIDER_URL = "https://ga.jspm.io/npm:";
const PACKAGE_BASE_PATH = "/package/";
const MAYBE_README_FILES = ["README.md", "readme.md"];
const SEARCH_RESULT_DEFAULT_PAGE_SIZE = 20;

const EXAMPLES_SOURCE_CODE_HTML_BROWSER = "examples-source-code-html-browser";
const EXAMPLES_GENERATED_CODE_HTML_BROWSER = "examples-generated-code-html-browser";
const EXAMPLES_GENERATED_CODE_IMPORTMAP_BROWSER =
    "examples-generated-code-importmap-browser";
const EXAMPLES_RENDER_HTML_BROWSER = "examples-render-html-browser";
const EXAMPLES_RENDER_DOMTREE = "examples-render-domtree";
const DEFAULT_EXAMPLES_CODE_ACTIVE_TAB = EXAMPLES_SOURCE_CODE_HTML_BROWSER;
const EXAMPLES_CODE_TAB = "examples-code";
const EXAMPLES_RENDER_TAB = "examples-render";

export { NPM_PROVIDER_URL, PACKAGE_BASE_PATH, MAYBE_README_FILES, SEARCH_RESULT_DEFAULT_PAGE_SIZE, EXAMPLES_CODE_TAB, EXAMPLES_RENDER_TAB, EXAMPLES_SOURCE_CODE_HTML_BROWSER, EXAMPLES_GENERATED_CODE_HTML_BROWSER, EXAMPLES_GENERATED_CODE_IMPORTMAP_BROWSER, EXAMPLES_RENDER_HTML_BROWSER, EXAMPLES_RENDER_DOMTREE, DEFAULT_EXAMPLES_CODE_ACTIVE_TAB };
