const NPM_PROVIDER_URL = "https://ga.jspm.io/npm:";
const PACKAGE_BASE_PATH = "/package/";
const MAYBE_README_FILES = ["README.md", "readme.md"];
const SEARCH_RESULT_DEFAULT_PAGE_SIZE = 20;

export { NPM_PROVIDER_URL, PACKAGE_BASE_PATH, MAYBE_README_FILES, SEARCH_RESULT_DEFAULT_PAGE_SIZE };
